<?php
/**
 * API Maintenance Mode - gaurosa.it
 * 
 * GET  → Stato attuale manutenzione
 * POST → Attiva/disattiva manutenzione
 * 
 * Autenticazione via SYNC_API_KEY (stessa chiave usata per sync prodotti)
 */

require_once __DIR__ . '/api-config.php';

$maintenanceFile = __DIR__ . '/maintenance.json';

// Default maintenance state
$defaultState = [
    'enabled' => false,
    'message' => 'Stiamo aggiornando il sito. Torna presto!',
    'allowed_ips' => [],
];

/**
 * Read current maintenance state
 */
function readMaintenanceState($file, $default) {
    if (!file_exists($file)) {
        return $default;
    }
    $data = json_decode(file_get_contents($file), true);
    if (!$data) {
        return $default;
    }
    return array_merge($default, $data);
}

/**
 * Write maintenance state
 */
function writeMaintenanceState($file, $state) {
    $result = file_put_contents($file, json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
    return $result !== false;
}

/**
 * Regenerate the "Maintenance mode" block in .htaccess with current allowed IPs.
 *
 * The .htaccess maintenance redirect runs BEFORE index.php, so the IP whitelist
 * MUST live in .htaccess (not in PHP) to actually bypass the redirect.
 *
 * This function rewrites the section between markers:
 *   # ── 0. Maintenance mode ─...
 *   ...
 *   ErrorDocument 503 /maintenance.html
 *
 * Each allowed IP becomes a `RewriteCond %{REMOTE_ADDR} !^IP$` line.
 */
function regenerateHtaccessMaintenanceBlock($htaccessFile, $allowedIps) {
    if (!file_exists($htaccessFile) || !is_writable($htaccessFile)) {
        return false;
    }

    $contents = file_get_contents($htaccessFile);
    if ($contents === false) {
        return false;
    }

    // Build IP exclusion conditions
    $ipConditions = '';
    foreach ($allowedIps as $ip) {
        // Validate IPv4 format strictly (refuse anything weird)
        if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
            // Escape dots for regex
            $escaped = str_replace('.', '\\.', $ip);
            $ipConditions .= "RewriteCond %{REMOTE_ADDR} !^{$escaped}$\n";
        }
    }

    // Build the new block
    $newBlock = "# ── 0. Maintenance mode ─────────────────────────────────────────────\n"
              . "# When .maintenance_enabled file exists, show maintenance page\n"
              . "# Excludes: API calls, maintenance page itself, maintenance API, whitelisted IPs\n"
              . "# AUTO-GENERATED by api-maintenance.php — do not edit manually\n"
              . "RewriteCond %{DOCUMENT_ROOT}/.maintenance_enabled -f\n"
              . $ipConditions
              . "RewriteCond %{REQUEST_URI} !^/api-\n"
              . "RewriteCond %{REQUEST_URI} !^/api/\n"
              . "RewriteCond %{REQUEST_URI} !^/maintenance\\.html$\n"
              . "RewriteCond %{REQUEST_URI} !^/maintenance\\.json$\n"
              . "RewriteRule ^.*\$ /maintenance.html [R=503,L]\n"
              . "ErrorDocument 503 /maintenance.html";

    // Replace the block between "# ── 0. Maintenance mode" and "ErrorDocument 503 /maintenance.html"
    $pattern = '/# ── 0\. Maintenance mode.*?ErrorDocument 503 \/maintenance\.html/s';
    $newContents = preg_replace($pattern, $newBlock, $contents, 1, $count);

    if ($count === 0 || $newContents === null) {
        // Block markers not found — abort to avoid corrupting .htaccess
        return false;
    }

    // Backup before write
    @copy($htaccessFile, $htaccessFile . '.bak');

    return file_put_contents($htaccessFile, $newContents) !== false;
}

// --- Handle OPTIONS (CORS preflight) ---
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    jsonResponse(['success' => true]);
}

// --- Authenticate ---
$body = getJsonBody();
$apiKey = $body['api_key'] 
    ?? $_SERVER['HTTP_X_API_KEY'] 
    ?? $_GET['api_key'] 
    ?? null;

if ($apiKey !== SYNC_API_KEY) {
    jsonResponse(['success' => false, 'error' => 'API key non valida'], 401);
}

// --- GET: Read maintenance state ---
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $state = readMaintenanceState($maintenanceFile, $defaultState);
    jsonResponse([
        'success' => true,
        'data' => $state,
    ]);
}

// --- POST: Toggle maintenance mode ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $currentState = readMaintenanceState($maintenanceFile, $defaultState);

    // Read parameters from body
    $enabled = $body['enabled'] ?? null;
    $message = $body['message'] ?? null;
    $allowedIps = $body['allowed_ips'] ?? null;

    // Update state
    if ($enabled !== null) {
        $currentState['enabled'] = (bool) $enabled;
    }
    if ($message !== null) {
        $currentState['message'] = (string) $message;
    }
    if ($allowedIps !== null && is_array($allowedIps)) {
        $currentState['allowed_ips'] = $allowedIps;
    }

    // Add timestamp
    if ($currentState['enabled']) {
        $currentState['enabled_at'] = date('Y-m-d H:i:s');
    } else {
        $currentState['enabled_at'] = null;
    }

    // Create/delete .maintenance_enabled flag file for .htaccess
    $flagFile = __DIR__ . '/.maintenance_enabled';
    if ($currentState['enabled']) {
        file_put_contents($flagFile, date('Y-m-d H:i:s'));
    } else {
        if (file_exists($flagFile)) {
            unlink($flagFile);
        }
    }

    // Regenerate .htaccess maintenance block with current allowed IPs
    // (.htaccess runs BEFORE index.php, so the whitelist must live there)
    $htaccessFile = __DIR__ . '/.htaccess';
    $htaccessUpdated = regenerateHtaccessMaintenanceBlock(
        $htaccessFile,
        $currentState['allowed_ips'] ?? []
    );

    // Write state
    if (writeMaintenanceState($maintenanceFile, $currentState)) {
        jsonResponse([
            'success' => true,
            'data' => $currentState,
            'htaccess_updated' => $htaccessUpdated,
            'message' => $currentState['enabled']
                ? 'Modalita manutenzione ATTIVATA'
                : 'Modalita manutenzione DISATTIVATA',
        ]);
    } else {
        jsonResponse([
            'success' => false,
            'error' => 'Errore scrittura file maintenance.json',
        ], 500);
    }
}

// --- Method not allowed ---
jsonResponse(['success' => false, 'error' => 'Metodo non supportato'], 405);
